/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainMenu.java
 *
 * Created on 2-jan-2011, 17:09:27
 */

package view;

import main.MainApplication;

/**
 *
 * @author Dark
 */
public class MainMenu extends javax.swing.JPanel {

    /** Creates new form MainMenu */
    public MainMenu() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        manageUsers = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        searchUpdates = new javax.swing.JButton();

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jButton1.setText("Main function");
        jPanel1.add(jButton1);
        jPanel1.add(jPanel2);

        manageUsers.setText("Manage users");
        manageUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUsersActionPerformed(evt);
            }
        });
        jPanel1.add(manageUsers);
        jPanel1.add(jPanel3);

        jButton3.setText("Something else");
        jPanel1.add(jButton3);
        jPanel1.add(jPanel4);

        searchUpdates.setText("Search updates");
        jPanel1.add(searchUpdates);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void manageUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUsersActionPerformed
        MainApplication.getInstance().showPanel(new AccountManager());
    }//GEN-LAST:event_manageUsersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton manageUsers;
    private javax.swing.JButton searchUpdates;
    // End of variables declaration//GEN-END:variables

}
